# Generated by Django 5.2.3 on 2025-06-25 15:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Унікальний зовнішній ідентифікатор для посилань (API, бот)', unique=True)),
                ('article', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='order_excels/')),
            ],
        ),
    ]
